/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c117b74356c8d377f638b42c775903b8)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	APP_ENV: "production";
	PRIVATE_MODE: "true";
	ACCESS_TEAM_DOMAIN: "https://square-bonus-81ca.cloudflareaccess.com";
	ACCESS_AUD: "24a32ac1fbea4bbfcde750e745927aba487081cb1ca2b481d729af48e1af4ce1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "PRIVATE_MODE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
